
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module taskIII(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
wire
	writeEnable,
	start,
	ready;
wire [13:0]
	addr;
wire [31:0]
    dataout;
wire [8:0]
	dim;
wire [5:0]
	hist_bins;
wire [5:0]
	addr_hist;
wire
	writeEnable_hist;
wire [31:0]
	datain_hist;


//=======================================================
//  Structural coding
//=======================================================

// Part III instance should go here!

// Do not touch
jtag_to_onchipmem_handler_32 uHandler(
	.clk(MAX10_CLK1_50),
	.rst_n(KEY[0]),
	.writeEnable(1'b0),
	.start(start),
	.addr(addr),
    .dataout(dataout),
	.ready(ready),
	.dim(dim),
	.hist_bins(hist_bins),
	.addr_hist(addr_hist),
	.writeEnable_hist(writeEnable_hist),
	.datain_hist(datain_hist)
);

endmodule
