
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module partII(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

always @(*) begin
	if (!SW[1] & SW[0])
		assign HEX0 = 8'b11111001;
	else 
		assign HEX0 = 8'b11111111;
end
endmodule
