
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module partII(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

//module dec_7seg_decoder
//(
//	input [2:0]
//			bin,
//	output [7:0]
//			hex0,
//			//hex1
//);


// Logic

// HEX0
assign HEX0[7] = 1;

assign HEX0[6] = (!SW[3] & !SW[2] & !SW[1]) | (SW[3] & !SW[2] & SW[1]) | (!SW[3] & SW[2] & SW[1] & SW[0]);

assign HEX0[5] = (!SW[3] & !SW[2] & SW[0]) | (!SW[3] & !SW[2] & SW[1]) | (!SW[3] & SW[1] & SW[0]) | (!SW[2] & SW[1] & SW[0]) | (SW[3] & SW[2] & !SW[1]);

assign HEX0[4] = (SW[0]) | (!SW[3] & SW[2] & !SW[1]) | (SW[3] & SW[2] & SW[1]);

assign HEX0[3] = (!SW[2] & !SW[1] & SW[0]) | (SW[3] & !SW[2] & SW[0]) | (!SW[3] & SW[2] & !SW[1] & !SW[0]) | (!SW[3] & SW[2] & SW[1] & SW[0]) | (SW[3] & SW[2] & SW[1] & !SW[0]);

assign HEX0[2] = (!SW[3] & !SW[2] & SW[1] & !SW[0]) | (SW[3] & SW[2] & !SW[1] & !SW[0]);

assign HEX0[1] = (!SW[3] & SW[2] & !SW[1] & SW[0]) | (!SW[3] & SW[2] & SW[1] & !SW[0]) | (SW[3] & SW[2] & SW[1] & SW[0]);

assign HEX0[0] = (!SW[3] & !SW[2] & !SW[1] & SW[0]) | (!SW[3] & SW[2] & !SW[1] & !SW[0]) | (SW[3] & !SW[2] & SW[1] & SW[0]) | (SW[3] & SW[2] & SW[1] & !SW[0]);


// HEX1
assign HEX1[7] = 1;

assign HEX1[6] = 1;

assign HEX1[5] = (SW[3] & SW[1]) | (SW[3] & SW[2]);

assign HEX1[4] = HEX1[5];

assign HEX1[3] = HEX1[5];

assign HEX1[2] = 0;

assign HEX1[1] = 0;

assign HEX1[0] = HEX1[5];

// Turn off the rest of the displays
assign HEX2 = 8'b11111111;
assign HEX3 = 8'b11111111;
assign HEX4 = 8'b11111111;
assign HEX5 = 8'b11111111;

endmodule
