
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module partI(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

// LEDR[2:0] corresponds to the number, 0, 1, 2, and 3. SW0, SW1, and SW2 could switch the LEDR to display those numbers if you set SW in the number's binary form.
assign LEDR[0] = SW[0] & !SW[1];
assign LEDR[1] = !SW[0] & SW[1];
assign LEDR[2] = SW[0] & SW[1];


// Display 0, 1, 2 in HEX0, HEX1, HEX2
//assign HEX0 = 8'b11000000;
//assign HEX1 = 8'b11111001;
//assign HEX2 = 8'b10100100;

endmodule
